### This script contains the following points:

#### 1. Importing Libraries
#### 2. Importing Data
#### 3. Aggregating mean of order_number grouped department_id for entire dataframe
#### 4. Analyze result
#### 5. Creating flags for Loyalty customers
#### 6. Customers spending habits comparison
#### 7. Creating Flag on price mean of Spender
#### 8. Create a flag for frequent users
#### 9. Export data as pkl

# 01. Importing Libraries

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import os

# 02. Importing Data

In [4]:
# Tell Python to remember a main folder path
path = r'C:\Users\Frederick\Documents\CareerFoundry\CF - Data Analytics Immersion\Achievement4\04-2024 Instacart Basket Analysis'

In [5]:
# Import data set
ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged_derived.pkl'))

# 03. Aggregating mean of order_number grouped department_id for entire dataframe

In [6]:
#Checking dataframe 
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,28,6,11,3.0,False,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,30,6,17,20.0,False,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,2,0,21,6.0,False,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,1,3,13,NaN,True,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,3,4,17,9.0,False,11,1,both,Mid-range product,Least busy,Slowest days,Average orders

In [7]:
# perform single aggregation mean of order number by department_id (average number of orders per user department id)
ords_prods_merge.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

# 4 Analyze result

There are 21 depatment_id's compared to the subset of 100000 there are only 8.

# 5 Creating flags for Loyalty customers

In [8]:
# Creating new column "max_order"
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

C:\Users\Frederick\AppData\Local\Temp\ipykernel_12452\2324063168.py:2: FutureWarning: The provided callable <function max at 0x000001351781F060> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [9]:
# Checking for new column
ords_prods_merge.head(20)

,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,...,days_since_prior_order,first_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,28,6,...,3.0,False,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,30,6,...,20.0,False,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,2,0,...,6.0,False,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,1,3,...,NaN,True,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,3,4,...,9.0,False,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,12372,1701441,777,16,1,...,26.0,False,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,13096,1871483,825,3,2,...,30.0,False,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,14603,1290456,910,12,3,...,30.0,False,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,17065,369558,1052,10,1,...,19.0,False,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,17070,589712,1052,15,1,...,15.0,False,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,22082,1798115,1379,1,5,...,NaN,True,1,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,23713,497193,1480,36,3,...,7.0,False,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,23715,1727826,1480,38,4,...,7.0,False,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,23716,2694698,1480,39,2,...,12.0,False,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,23937,3171753,1494,6,3,...,2.0,False,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,23938,186761,1494,7,2,...,6.0,False,18,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,23940,317121,1494,9,5,...,10.0,False,12,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,24740,200390,1540,4,2,...,7.0,False,10,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,24741,374436,1540,5,1,...,6.0,False,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,24742,2920553,1540,6,1,...,14.0,False,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28

In [10]:
# Assign loyalty flag
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [11]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [12]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [13]:
# Check loyalty flags
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [13]:
# Check Loyalty flag in dataframe
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(20)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6

# 6 Customers spending habits comparison

In [14]:
# the min max and mean of each loyalty flag
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

Loyal customer spend the least , new customer spend the most , and regular customer falls in between. This is seen by observing the mean.

# 7 Creating Flag on price mean of Spender

In [15]:
# Creating column for average spender
ords_prods_merge['average_spend'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

C:\Users\Frederick\AppData\Local\Temp\ipykernel_12452\2579547553.py:2: FutureWarning: The provided callable <function mean at 0x000001351781FA60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['average_spend'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [16]:
# Checking the new column
ords_prods_merge.head(20)

,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,...,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend
0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,28,6,...,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,30,6,...,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,2,0,...,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,1,3,...,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,3,4,...,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414
5,1,Chocolate Sandwich Cookies,61,19,5.8,12372,1701441,777,16,1,...,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26,Regular customer,6.935398
6,1,Chocolate Sandwich Cookies,61,19,5.8,13096,1871483,825,3,2,...,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576
7,1,Chocolate Sandwich Cookies,61,19,5.8,14603,1290456,910,12,3,...,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12,Regular customer,6.680000
8,1,Chocolate Sandwich Cookies,61,19,5.8,17065,369558,1052,10,1,...,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20,Regular customer,7.162500
9,1,Chocolate Sandwich Cookies,61,19,5.8,17070,589712,1052,15,1,...,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20,Regular customer,7.162500
10,1,Chocolate Sandwich Cookies,61,19,5.8,22082,1798115,1379,1,5,...,1,0,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636
11,1,Chocolate Sandwich Cookies,61,19,5.8,23713,497193,1480,36,3,...,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43,Loyal customer,5.081633
12,1,Chocolate Sandwich Cookies,61,19,5.8,23715,1727826,1480,38,4,...,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43,Loyal customer,5.081633
13,1,Chocolate Sandwich Cookies,61,19,5.8,23716,2694698,1480,39,2,...,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633
14,1,Chocolate Sandwich Cookies,61,19,5.8,23937,3171753,1494,6,3,...,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13,Regular customer,6.803797
15,1,Chocolate Sandwich Cookies,61,19,5.8,23938,186761,1494,7,2,...,18,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797
16,1,Chocolate Sandwich Cookies,61,19,5.8,23940,317121,1494,9,5,...,12,1,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797
17,1,Chocolate Sandwich Cookies,61,19,5.8,24740,200390,1540,4,2,...,10,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122
18,1,Chocolate Sandwich Cookies,61,19,5.8,24741,374436,1540,5,1,...,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122
19,1,Chocolate Sandwich Cookies,61,19,5.8,24742,2920553,1540,6,1,...,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122

In [17]:
# Creating flag for low and high spender
ords_prods_merge.loc[ords_prods_merge['average_spend']<10,'spender_flag']='Low_spender'

In [18]:
ords_prods_merge.loc[ords_prods_merge['average_spend']>= 10, 'spender_flag'] = 'High_spender'

In [19]:
# Check spender flags
ords_prods_merge['spender_flag'].value_counts(dropna = False)

spender_flag
Low_spender     31770614
High_spender      634245
Name: count, dtype: int64

In [20]:
ords_prods_merge[['user_id', 'average_spend', 'spender_flag', 'prices']].head(60)

    user_id  average_spend spender_flag  prices
0       138       6.935811  Low_spender     5.8
1       138       6.935811  Low_spender     5.8
2       709       7.930208  Low_spender     5.8
3       764       4.972414  Low_spender     5.8
4       764       4.972414  Low_spender     5.8
5       777       6.935398  Low_spender     5.8
6       825       5.957576  Low_spender     5.8
7       910       6.680000  Low_spender     5.8
8      1052       7.162500  Low_spender     5.8
9      1052       7.162500  Low_spender     5.8
10     1379       5.813636  Low_spender     5.8
11     1480       5.081633  Low_spender     5.8
12     1480       5.081633  Low_spender     5.8
13     1480       5.081633  Low_spender     5.8
14     1494       6.803797  Low_spender     5.8
15     1494       6.803797  Low_spender     5.8
16     1494       6.803797  Low_spender     5.8
17     1540       6.607122  Low_spender     5.8
18     1540       6.607122  Low_spender     5.8
19     1540       6.607122  Low_spender     5.8
20     1540       6.607122  Low_spender     5.8
21     1540       6.607122  Low_spender     5.8
22     1540       6.607122  Low_spender     5.8
23     1540       6.607122  Low_spender     5.8
24     1540       6.607122  Low_spender     5.8
25     1540       6.607122  Low_spender     5.8
26     1540       6.607122  Low_spender     5.8
27     1540       6.607122  Low_spender     5.8
28     1540       6.607122  Low_spender     5.8
29     1540       6.607122  Low_spender     5.8
30     1540       6.607122  Low_spender     5.8
31     1540       6.607122  Low_spender     5.8
32     1540       6.607122  Low_spender     5.8
33     1540       6.607122  Low_spender     5.8
34     1598       7.123529  Low_spender     5.8
35     1598       7.123529  Low_spender     5.8
36     1598       7.123529  Low_spender     5.8
37     1647       4.853521  Low_spender     5.8
38     1647       4.853521  Low_spender     5.8
39     1647       4.853521  Low_spender     5.8
40     1647       4.853521  Low_spender     5.8
41     1647       4.853521  Low_spender     5.8
42     2833       7.377143  Low_spender     5.8
43     2850       8.054153  Low_spender     5.8
44     2857       8.353793  Low_spender     5.8
45     3010       6.452800  Low_spender     5.8
46     3029       7.960606  Low_spender     5.8
47     3395       6.322222  Low_spender     5.8
48     3904       7.511111  Low_spender     5.8
49     4006       7.441100  Low_spender     5.8
50     4006       7.441100  Low_spender     5.8
51     4006       7.441100  Low_spender     5.8
52     4006       7.441100  Low_spender     5.8
53     4006       7.441100  Low_spender     5.8
54     4122       7.598765  Low_spender     5.8
55     4141       6.033333  Low_spender     5.8
56     4343       7.393939  Low_spender     5.8
57     4553       5.715789  Low_spender     5.8
58     4845       7.229630  Low_spender     5.8
59     6866       4.807143  Low_spender     5.8

# 8 Create a flag for frequent users

In [21]:
# Create a column for frequet users
ords_prods_merge['Customer_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

C:\Users\Frederick\AppData\Local\Temp\ipykernel_12452\3165240341.py:2: FutureWarning: The provided callable <function median at 0x00000135179542C0> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['Customer_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [22]:
# Cheaking for new column
ords_prods_merge.head(20)

,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0,order_id,user_id,order_number,orders_day_of_week,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_spend,spender_flag,Customer_frequency
0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,28,6,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,32,Regular customer,6.935811,Low_spender,8.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,30,6,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,32,Regular customer,6.935811,Low_spender,8.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,2,0,...,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low_spender,8.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,1,3,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low_spender,9.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,3,4,...,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low_spender,9.0
5,1,Chocolate Sandwich Cookies,61,19,5.8,12372,1701441,777,16,1,...,both,Mid-range product,Regularly busy,Busiest days,Average orders,26,Regular customer,6.935398,Low_spender,11.0
6,1,Chocolate Sandwich Cookies,61,19,5.8,13096,1871483,825,3,2,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,9,New customer,5.957576,Low_spender,20.0
7,1,Chocolate Sandwich Cookies,61,19,5.8,14603,1290456,910,12,3,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,12,Regular customer,6.680000,Low_spender,6.0
8,1,Chocolate Sandwich Cookies,61,19,5.8,17065,369558,1052,10,1,...,both,Mid-range product,Regularly busy,Busiest days,Average orders,20,Regular customer,7.162500,Low_spender,10.0
9,1,Chocolate Sandwich Cookies,61,19,5.8,17070,589712,1052,15,1,...,both,Mid-range product,Regularly busy,Busiest days,Most orders,20,Regular customer,7.162500,Low_spender,10.0
10,1,Chocolate Sandwich Cookies,61,19,5.8,22082,1798115,1379,1,5,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,10,New customer,5.813636,Low_spender,20.0
11,1,Chocolate Sandwich Cookies,61,19,5.8,23713,497193,1480,36,3,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,43,Loyal customer,5.081633,Low_spender,7.0
12,1,Chocolate Sandwich Cookies,61,19,5.8,23715,1727826,1480,38,4,...,both,Mid-range product,Least busy,Slowest days,Most orders,43,Loyal customer,5.081633,Low_spender,7.0
13,1,Chocolate Sandwich Cookies,61,19,5.8,23716,2694698,1480,39,2,...,both,Mid-range product,Regularly busy,Regularly busy,Most orders,43,Loyal customer,5.081633,Low_spender,7.0
14,1,Chocolate Sandwich Cookies,61,19,5.8,23937,3171753,1494,6,3,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,13,Regular customer,6.803797,Low_spender,7.0
15,1,Chocolate Sandwich Cookies,61,19,5.8,23938,186761,1494,7,2,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797,Low_spender,7.0
16,1,Chocolate Sandwich Cookies,61,19,5.8,23940,317121,1494,9,5,...,both,Mid-range product,Regularly busy,Regularly busy,Average orders,13,Regular customer,6.803797,Low_spender,7.0
17,1,Chocolate Sandwich Cookies,61,19,5.8,24740,200390,1540,4,2,...,both,Mid-range product,Regularly busy,Regularly busy,Fewest orders,28,Regular customer,6.607122,Low_spender,7.0
18,1,Chocolate Sandwich Cookies,61,19,5.8,24741,374436,1540,5,1,...,both,Mid-range product,Regularly busy,Busiest days,Average orders,28,Regular customer,6.607122,Low_spender,7.0
19,1,Chocolate Sandwich Cookies,61,19,5.8,24742,2920553,1540,6,1,...,both,Mid-range product,Regularly busy,Busiest days,Fewest orders,28,Regular customer,6.607122,Low_spender,7.0

In [23]:
# Creating flag on order frequency
ords_prods_merge.loc[ords_prods_merge['Customer_frequency'] > 20, 'frequency_flag'] = 'Non_frequent_customer'

In [24]:
ords_prods_merge.loc[(ords_prods_merge['Customer_frequency']>10) & (ords_prods_merge['Customer_frequency']<=20),
                     'frequency_flag'] = 'Regular customer'

In [25]:
ords_prods_merge.loc[ords_prods_merge['Customer_frequency'] <= 10, 'frequency_flag'] = 'Frequent Customer'

In [26]:
# Check frequency flags
ords_prods_merge['frequency_flag'].value_counts(dropna = False)

frequency_flag
Frequent Customer        21559853
Regular customer          7208564
Non_frequent_customer     3636437
nan                             5
Name: count, dtype: int64

In [27]:
#Checking for columns
ords_prods_merge[['user_id', 'Customer_frequency', 'frequency_flag']].head(60)

    user_id  Customer_frequency         frequency_flag
0       138                 8.0      Frequent Customer
1       138                 8.0      Frequent Customer
2       709                 8.0      Frequent Customer
3       764                 9.0      Frequent Customer
4       764                 9.0      Frequent Customer
5       777                11.0       Regular customer
6       825                20.0       Regular customer
7       910                 6.0      Frequent Customer
8      1052                10.0      Frequent Customer
9      1052                10.0      Frequent Customer
10     1379                20.0       Regular customer
11     1480                 7.0      Frequent Customer
12     1480                 7.0      Frequent Customer
13     1480                 7.0      Frequent Customer
14     1494                 7.0      Frequent Customer
15     1494                 7.0      Frequent Customer
16     1494                 7.0      Frequent Customer
17     1540                 7.0      Frequent Customer
18     1540                 7.0      Frequent Customer
19     1540                 7.0      Frequent Customer
20     1540                 7.0      Frequent Customer
21     1540                 7.0      Frequent Customer
22     1540                 7.0      Frequent Customer
23     1540                 7.0      Frequent Customer
24     1540                 7.0      Frequent Customer
25     1540                 7.0      Frequent Customer
26     1540                 7.0      Frequent Customer
27     1540                 7.0      Frequent Customer
28     1540                 7.0      Frequent Customer
29     1540                 7.0      Frequent Customer
30     1540                 7.0      Frequent Customer
31     1540                 7.0      Frequent Customer
32     1540                 7.0      Frequent Customer
33     1540                 7.0      Frequent Customer
34     1598                 2.0      Frequent Customer
35     1598                 2.0      Frequent Customer
36     1598                 2.0      Frequent Customer
37     1647                25.0  Non_frequent_customer
38     1647                25.0  Non_frequent_customer
39     1647                25.0  Non_frequent_customer
40     1647                25.0  Non_frequent_customer
41     1647                25.0  Non_frequent_customer
42     2833                13.0       Regular customer
43     2850                 7.0      Frequent Customer
44     2857                11.0       Regular customer
45     3010                 7.0      Frequent Customer
46     3029                28.0  Non_frequent_customer
47     3395                18.0       Regular customer
48     3904                21.0  Non_frequent_customer
49     4006                 7.0      Frequent Customer
50     4006                 7.0      Frequent Customer
51     4006                 7.0      Frequent Customer
52     4006                 7.0      Frequent Customer
53     4006                 7.0      Frequent Customer
54     4122                 7.0      Frequent Customer
55     4141                30.0  Non_frequent_customer
56     4343                30.0  Non_frequent_customer
57     4553                30.0  Non_frequent_customer
58     4845                20.0       Regular customer
59     6866                30.0  Non_frequent_customer

# 9 Export data as pkl

In [28]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'aggregated_ords_prods_merge.pkl'))